source "http://rubygems.org"
gem "sinatra", "~> 2.2"
gem "pg", "~> 1.4"
gem "yaml", "~> 0.2.0"
gem "rspec", "~> 3.11"
gem "rack", "~> 2.2"
gem "rack-test", "~> 2.0"
gem "rails-helper", "~> 0.1.0"
gem "rake", "~> 13.0.6"
